### ISSUE TITLE
There is no "vanishing_angle" in the provided MHNet prediction results

### ISSUE THREAD

**Issue by xl-huo** [zillow/salve#3]
When I tried to generate alignment hypotheses using `scripts/export_alignment_hypotheses.py`, an error occurred showing that  
```                  
FileNotFoundError: No file found at src/ZInD_HorizonNet_predictions/vanishing_angle/0038/floor_01_partial_room_02_pano_10.json  
```
It seems that the [L174](https://github.com/zillow/salve/blob/fda014f3f8d164f5092cdcc15f4047f873992601/salve/dataset/hnet_prediction_loader.py#L174) of `salve/dataset/hnet_predicion_loader.py` looks for `vanishing_angle` in the HMNet predictions, in which the provided predictions downloaded through [Goolge drive](https://files-zillowstatic-com.s3.us-west-2.amazonaws.com/research/public/StaticFiles/salve/data/ZInD_HorizonNet_predictions.tar.gz) do not contain.

Could you please upload the complete prediction results? Thank you!

**Comment by zcq15** [comment]
Hello! I'm also having this issue, may I please if you have solved the issue?

**Comment by yuguang-li** [comment]
Thanks for reporting the issue. I just uploaded a commit with the missing vanishing angle prediction file, under `assets/zind_vanishing_angles.csv`. Please also check out the changes in `README.md` file for usage.
